# Generated by Django 4.2.1 on 2023-05-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_range', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'verbose_name': 'Currency Value',
                'verbose_name_plural': 'Currency Values',
            },
        ),
        migrations.CreateModel(
            name='CurrencyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('code', models.CharField(max_length=3)),
                ('currency_names', models.ManyToManyField(related_name='currency_values', to='currency.currencyvalue')),
            ],
            options={
                'verbose_name': 'Currency Name',
                'verbose_name_plural': 'Currency Names',
            },
        ),
        migrations.CreateModel(
            name='CurrencyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('currency_names', models.ManyToManyField(related_name='currency_dates', to='currency.currencyname')),
            ],
            options={
                'verbose_name': 'Currency Date',
                'verbose_name_plural': 'Currency Dates',
            },
        ),
    ]
