# Generated by Django 4.2.1 on 2023-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyname',
            name='currency_names',
        ),
        migrations.AddField(
            model_name='currencyvalue',
            name='currency_names',
            field=models.ManyToManyField(related_name='currency_values', to='currency.currencyname'),
        ),
    ]
