# Generated by Django 4.2.1 on 2023-05-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_remove_currencydate_currency_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydate',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
    ]
